### PR TITLE
Avoid using the deprecated functions

### LINKED ISSUE #46: goal_oriented_elastoplasticity: Deprecation warnings with deal.II 9.0
```
code-gallery/goal_oriented_elastoplasticity % make
Scanning dependencies of target elastoplastic
[ 50%] Building CXX object CMakeFiles/elastoplastic.dir/elastoplastic.cc.o
/home/tamiko/workspace/dealii/code-gallery/goal_oriented_elastoplasticity/elastoplastic.cc:3790:28: warning: 'set_manifold' is deprecated [-Wdeprecated-declarations]
          triangulation_2d.set_manifold (10);
                           ^
/usr/include/deal.II/grid/tria.h:1811:3: note: 'set_manifold' has been explicitly marked deprecated here
  DEAL_II_DEPRECATED
  ^
/usr/include/deal.II/base/config.h:95:30: note: expanded from macro 'DEAL_II_DEPRECATED'
#define DEAL_II_DEPRECATED [[deprecated]]
                             ^
/home/tamiko/workspace/dealii/code-gallery/goal_oriented_elastoplasticity/elastoplastic.cc:7219:23: warning: 'set_manifold' is deprecated [-Wdeprecated-declarations]
        triangulation.set_manifold (0);
                      ^
/home/tamiko/workspace/dealii/code-gallery/goal_oriented_elastoplasticity/elastoplastic.cc:7255:17: note: in instantiation of member function 'ElastoPlastic::ElastoPlasticProblem<3>::run'
      requested here
        problem.run();
                ^
/usr/include/deal.II/grid/tria.h:1811:3: note: 'set_manifold' has been explicitly marked deprecated here
  DEAL_II_DEPRECATED
  ^
/usr/include/deal.II/base/config.h:95:30: note: expanded from macro 'DEAL_II_DEPRECATED'
#define DEAL_II_DEPRECATED [[deprecated]]
                             ^
/home/tamiko/workspace/dealii/code-gallery/goal_oriented_elastoplasticity/elastoplastic.cc:7220:23: warning: 'set_manifold' is deprecated [-Wdeprecated-declarations]
        triangulation.set_manifold (1);
                      ^
/usr/include/deal.II/grid/tria.h:1811:3: note: 'set_manifold' has been explicitly marked deprecated here
  DEAL_II_DEPRECATED
  ^
/usr/include/deal.II/base/config.h:95:30: note: expanded from macro 'DEAL_II_DEPRECATED'
#define DEAL_II_DEPRECATED [[deprecated]]
                             ^
/home/tamiko/workspace/dealii/code-gallery/goal_oriented_elastoplasticity/elastoplastic.cc:7224:23: warning: 'set_manifold' is deprecated [-Wdeprecated-declarations]
        triangulation.set_manifold (10);
                      ^
/usr/include/deal.II/grid/tria.h:1811:3: note: 'set_manifold' has been explicitly marked deprecated here
  DEAL_II_DEPRECATED
  ^
/usr/include/deal.II/base/config.h:95:30: note: expanded from macro 'DEAL_II_DEPRECATED'
#define DEAL_II_DEPRECATED [[deprecated]]
                             ^
/home/tamiko/workspace/dealii/code-gallery/goal_oriented_elastoplasticity/elastoplastic.cc:3651:23: warning: 'set_manifold' is deprecated [-Wdeprecated-declarations]
        triangulation.set_manifold (0);
                      ^
/home/tamiko/workspace/dealii/code-gallery/goal_oriented_elastoplasticity/elastoplastic.cc:7090:5: note: in instantiation of member function
      'ElastoPlastic::ElastoPlasticProblem<3>::make_grid' requested here
    make_grid();
    ^
/home/tamiko/workspace/dealii/code-gallery/goal_oriented_elastoplasticity/elastoplastic.cc:7255:17: note: in instantiation of member function 'ElastoPlastic::ElastoPlasticProblem<3>::run'
      requested here
        problem.run();
                ^
/usr/include/deal.II/grid/tria.h:1811:3: note: 'set_manifold' has been explicitly marked deprecated here
  DEAL_II_DEPRECATED
  ^
/usr/include/deal.II/base/config.h:95:30: note: expanded from macro 'DEAL_II_DEPRECATED'
#define DEAL_II_DEPRECATED [[deprecated]]
                             ^
/home/tamiko/workspace/dealii/code-gallery/goal_oriented_elastoplasticity/elastoplastic.cc:3652:23: warning: 'set_manifold' is deprecated [-Wdeprecated-declarations]
        triangulation.set_manifold (1);
                      ^
/usr/include/deal.II/grid/tria.h:1811:3: note: 'set_manifold' has been explicitly marked deprecated here
  DEAL_II_DEPRECATED
  ^
/usr/include/deal.II/base/config.h:95:30: note: expanded from macro 'DEAL_II_DEPRECATED'
#define DEAL_II_DEPRECATED [[deprecated]]
                             ^
/home/tamiko/workspace/dealii/code-gallery/goal_oriented_elastoplasticity/elastoplastic.cc:3790:28: warning: 'set_manifold' is deprecated [-Wdeprecated-declarations]
          triangulation_2d.set_manifold (10);
                           ^
/usr/include/deal.II/grid/tria.h:1811:3: note: 'set_manifold' has been explicitly marked deprecated here
  DEAL_II_DEPRECATED
  ^
/usr/include/deal.II/base/config.h:95:30: note: expanded from macro 'DEAL_II_DEPRECATED'
#define DEAL_II_DEPRECATED [[deprecated]]
                             ^
/home/tamiko/workspace/dealii/code-gallery/goal_oriented_elastoplasticity/elastoplastic.cc:3871:23: warning: 'set_manifold' is deprecated [-Wdeprecated-declarations]
        triangulation.set_manifold (10);
                      ^
/usr/include/deal.II/grid/tria.h:1811:3: note: 'set_manifold' has been explicitly marked deprecated here
  DEAL_II_DEPRECATED
  ^
/usr/include/deal.II/base/config.h:95:30: note: expanded from macro 'DEAL_II_DEPRECATED'
#define DEAL_II_DEPRECATED [[deprecated]]
```

### LINKED ISSUE #47: Quasi_static_Finite_strain_Quasi_incompressible_ViscoElasticity: Deprecation warnings with deal.II 9.0
```
/home/tamiko/workspace/dealii/code-gallery/Quasi_static_Finite_strain_Quasi_incompressible_ViscoElasticity/viscoelastic_strip_with_hole.cc:1321:22: warning: 'set_manifold' is deprecated
      [-Wdeprecated-declarations]
    tria_2d_not_flat.set_manifold(10); // Clear manifold
                     ^
/usr/include/deal.II/grid/tria.h:1811:3: note: 'set_manifold' has been explicitly marked deprecated here
  DEAL_II_DEPRECATED
  ^
/usr/include/deal.II/base/config.h:95:30: note: expanded from macro 'DEAL_II_DEPRECATED'
#define DEAL_II_DEPRECATED [[deprecated]]
                             ^
/home/tamiko/workspace/dealii/code-gallery/Quasi_static_Finite_strain_Quasi_incompressible_ViscoElasticity/viscoelastic_strip_with_hole.cc:1321:22: warning: 'set_manifold' is deprecated
      [-Wdeprecated-declarations]
    tria_2d_not_flat.set_manifold(10); // Clear manifold
                     ^
/home/tamiko/workspace/dealii/code-gallery/Quasi_static_Finite_strain_Quasi_incompressible_ViscoElasticity/viscoelastic_strip_with_hole.cc:1036:5: note: in instantiation of member function
      'ViscoElasStripHole::Solid<2>::make_2d_quarter_plate_with_hole' requested here
    make_2d_quarter_plate_with_hole(triangulation,
    ^
/usr/include/deal.II/grid/tria.h:1811:3: note: 'set_manifold' has been explicitly marked deprecated here
  DEAL_II_DEPRECATED
  ^
/usr/include/deal.II/base/config.h:95:30: note: expanded from macro 'DEAL_II_DEPRECATED'
#define DEAL_II_DEPRECATED [[deprecated]]
                             ^
/home/tamiko/workspace/dealii/code-gallery/Quasi_static_Finite_strain_Quasi_incompressible_ViscoElasticity/viscoelastic_strip_with_hole.cc:1321:22: warning: 'set_manifold' is deprecated
      [-Wdeprecated-declarations]
    tria_2d_not_flat.set_manifold(10); // Clear manifold
                     ^
/home/tamiko/workspace/dealii/code-gallery/Quasi_static_Finite_strain_Quasi_incompressible_ViscoElasticity/viscoelastic_strip_with_hole.cc:1111:5: note: in instantiation of member function
      'ViscoElasStripHole::Solid<3>::make_2d_quarter_plate_with_hole' requested here
    make_2d_quarter_plate_with_hole(tria_2d,
    ^
/usr/include/deal.II/grid/tria.h:1811:3: note: 'set_manifold' has been explicitly marked deprecated here
  DEAL_II_DEPRECATED
  ^
/usr/include/deal.II/base/config.h:95:30: note: expanded from macro 'DEAL_II_DEPRECATED'
#define DEAL_II_DEPRECATED [[deprecated]]
                             ^
```

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #46, fixes #47. Also make sure that variables are initialized.

### CODE REVIEW

**Comment by jppelteret** [comment]
BTW. Thanks for making these changes, and specifically fixing my code-gallery example.

**Comment by masterleinad** [comment]
> For these changes to be valid we'll have to update the minimum deal.II version to 9.0, won't we?

Yes, let me do this in another PR.

**Comment by jppelteret** [comment]
> Yes, let me do this in another PR.

I would have thought that it would make sense to do this in the same PR that technically breaks the configuration of these programs.

**Comment by masterleinad** [comment]
> I would have thought that it would make sense to do this in the same PR that technically breaks the configuration of these programs.

Alright, here you go! I just increased the required version for all the programs (except for `Ceres` which is taken care of in #45 resp. tamiko/code-gallery#1) to be on the safe side.

**Comment by jppelteret** [comment]
I'm sorry, I don't think that this is right. I was hoping for a correction to just these programs (I was about to add the patch to this PR myself). The others don't necessarily need a version bump, so should we in fact be enforcing it?

May we please restrict the patch to the examples covered here, and put the rest in another PR? If I knew that this is what you had intended to do then I would have made this comment before you implemented it.

**Comment by jppelteret** [comment]
Thanks @masterleinad :-)

**Comment by masterleinad** [comment]
> May we please restrict the patch to the examples covered here, and put the rest in another PR?

Done.

**Pull request merged**
