### PR TITLE
Removes a redundant edge from Nonlinear_PoroViscoelasticity tutorial dependencies

### PR DESCRIPTION
**Pull request by krishnakumarg1984**

### CODE REVIEW

**Comment by krishnakumarg1984** [comment]
Thanks for merging

**Comment by jppelteret** [comment]
Thanks for the fix. The original list better reflected how we went about developing this code, but the amendment makes sense in terms of what we're trying to show in the tutorial graph.

**Comment by krishnakumarg1984** [comment]
I see. I didn't know about the background. I just thought that the tutorial flow-diagram looked a bit messy :)

**Comment by jppelteret** [comment]
And I haven't seen what the graph looked like before the patch was merged :-D As I said, it felt right to add all of those entries in when we documented the code, but I think that your changes are ultimately correct and in the spirit of what information we're trying to transmit to everyone.

**Pull request merged**
