### PR TITLE
Initial source code and documentation for nonlinear poro-viscoelasticity

### PR DESCRIPTION
**Pull request by ecomellas**
Hi!

Here is a nonlinear poro-viscoelastic formulation that J-P Pelteret and I implemented in deal.ii to explore the porous and viscous contributions in brain mechanics applications. Our paper just got accepted and we said that the code would be available in the deal.ii code gallery, so I hope we can make this happen!

Thanks, 
Ester

### CODE REVIEW

**Comment by jppelteret** [comment]
Hey @ecomellas! Thanks a lot for opening this PR for our work. It's really cool that you've made all this effort to make the results in the paper completely reproducible. I just need a few days before I can take a thorough look through it, but I'll get to it as soon as I can :-)

**Comment by jppelteret** [comment]
@ecomellas Talking points for later:
- Zenodo: Canonical version of code
- Small sample of results in README. Maybe one video and a plot showing fundamental behaviour?
- Update to `p::s::Tria`

**Comment by jppelteret** [comment]
Hey @ecomellas! Does this look ok to you? I took only the first cycle (which should then be looped), and reduced the frame rate and image dimensions. This is about 4Mb in size. My other attempts were about 15x larger!

output_optimized

I know that the image quality is not super good, but I'm not sure how much better I can get it while keeping the file size down. Gifs are just not a great format for this sort of movie! If you have a Youtube account, we could host it there. If not then Wolfgang is willing to host it.

**Comment by bangerth** [comment]
I'm also happy to generate the movie for you guys once you've finalized the code and tell me how to run it!

**Comment by ecomellas** [comment]
@jppelteret I think the quality of the animation is good enough to show the behaviour of the poro-viscoelastic material. Indeed, it is a bit "grainy", but it gets the message across, doesn't it? I feel it will be tidier if the movie is in the code gallery website, rather than linking to a youtube account. But you're the experts, I leave it up to you to decide what's best!

**Comment by jppelteret** [comment]
> I'm also happy to generate the movie for you guys once you've finalized the code and tell me how to run it!

Thanks @bangerth! We've actually got the movie already, and were wanting to convert it to something embeddable in the README file.

> I think the quality of the animation is good enough to show the behaviour of the poro-viscoelastic material. Indeed, it is a bit "grainy", but it gets the message across, doesn't it? I feel it will be tidier if the movie is in the code gallery website, rather than linking to a youtube account. But you're the experts, I leave it up to you to decide what's best!

Ok, since you're happy with this animation then we can leave it as it is. That said, there's [a neat little trick](https://stackoverflow.com/a/29842302) to make the animation clickable and link to another site (e.g. a youtube page). So (with your permission) I might just ask @bangerth to host the movie, since he hosts many of the other deal.II videos, and then we get the best of both worlds. Does that sounds like a good plan to you?

**Comment by ecomellas** [comment]
Sound like a great plan @jppelteret! Let's do as you propose.

**Comment by ecomellas** [comment]
Sorry for the delay! I've now updated the results section in the readme.md file. @jppelteret feel free to correct my English, and rewrite or delete parts of the section so that it is more in line with the standards of deal.ii documentation.

**Comment by jppelteret** [comment]
Awesome, thanks a lot @ecomellas! I just got to skim over it and it looks like you really got stuck into it! Thank you so much :-) I'd like to take my time and read over it slowly, so I think that I'd likely wait until the weekend to do this. But I'd be happy to take it from here, and I'm sure that anything that I add would just be minor adjustments. Thank you very much again for taking the time to put together this really great code-gallery project!

**Comment by jppelteret** [comment]
Hi @ecomellas! Thanks for writing the awesome results section. If you're happy with the edits that I made there, then I can squash (compress) all of the commits after the very first one and we can then merge the new contribution into the code-gallery :-)

**Comment by ecomellas** [comment]
Hi @jppelteret! One last edit: I added the reference to the Glasgow talk where the question "Where is all that energy going?" came up for the first time. I wrote out the full reference in the readme.md, but we could just put a link to the paper on ResearchGate if you think it will look tidier. It's up to you! I'm happy both ways. Once you approve these last changes, go ahead and merge the new contribution to the code gallery. Thanks for your insightful suggestions!

**Comment by jppelteret** [comment]
Hi @ecomellas! I think that what you did was fine, and if you feel so inclined we could always update the README with a link to the paper/slides at a later stage. Congratulations again on the fantastic contribution :-) It's really cool!

**Pull request merged**
