### PR TITLE
Update precice to v3.

### PR DESCRIPTION
**Pull request by marcfehling**
Let's see if `coupled_laplace_problem` is happy.

### CODE REVIEW

**Comment by marcfehling** [comment]
Unfortunately not :-(
```
[ 25%] Building CXX object CMakeFiles/coupled_laplace_problem.dir/coupled_laplace_problem.cc.o
/__w/code-gallery/code-gallery/coupled_laplace_problem/coupled_laplace_problem.cc:31:10: fatal error: precice/SolverInterface.hpp: No such file or directory
   31 | #include <precice/SolverInterface.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by bangerth** [comment]
Do we know who we'd have to tag?

**Comment by marcfehling** [comment]
@davidscn -- We just tried out to update the precice version to the latest one, and it turns out that there are some incompatibilities with your code gallery program `coupled_laplace_problem`.

What is your intention with the code gallery program? Would you like to maintain compatibility with precice 2, or do you plan to have it running with v3? If so, would you help us making it compatible with v3?

This has no high priority, so don't feel obliged to address it right away. Your code still runs fine with precice 2 :)

Follow-up to #140.

**Comment by davidscn** [comment]
> What is your intention with the code gallery program? Would you like to maintain compatibility with precice 2, or do you plan to have it running with v3? If so, would you help us making it compatible with v3?

Updating to v3 seems a good idea, as it comes with major improvements in terms of internals and the API (_unbiased opinion_). WIP: #168

**Comment by marcfehling** [comment]
Superseded by #168

**Pull request closed without merging**
