### PR TITLE
Fixed Some Syntax Errors

### PR DESCRIPTION
**Pull request by Sam0h51**
I went back through the README.md and the Generalized-Swift-Hohenberg-Solver.cc files and made some syntax changes. I adjusted how I was declaring the matrices in the README, and I changed the path on the inline images so that they will render correctly. In the .cc file, I changed the style of the doxygen comments to better handle multi-line descriptions.

### CODE REVIEW

**Review by marcfehling — APPROVED** [review]

**Comment by marcfehling** [comment]
Your commit states "hopefully" it will fix the problem. You can build the documentation on your local machine. Please have a look at the code-gallery README.

**Comment by bangerth** [comment]
Let's see what happens. It isn't going to make things worse in any case.

**Comment by bangerth** [comment]
Update to #146.

**Comment by bangerth** [comment]
OK, at least the pictures now show up correctly. @Sam0h51: Are the formulas at https://dealii.org/developer/doxygen/deal.II/code_gallery_Swift_Hohenberg-Solver.html as you want them?

**Comment by Sam0h51** [comment]
Unfortunately they aren't. The matrices still aren't showing up as matrices, and it seems the comment blocks I reformatted have just disappeared.

**Pull request merged**
