### PR TITLE
Solver for incompressible NS based on Discontinuous Galerkin TR-BDF2 implemented with MatrixFree

### PR DESCRIPTION
**Pull request by GiuseppeOrlando878776**

### CODE REVIEW

**Comment by peterrum** [comment]
Looks nice! Let me post some comments via diff:

```diff
diff --git a/NavierStokes_TRBDF2_DG/README.md b/NavierStokes_TRBDF2_DG/README.md
index e490b57..87f3c29 100644
--- a/NavierStokes_TRBDF2_DG/README.md
+++ b/NavierStokes_TRBDF2_DG/README.md
@@ -30,7 +30,7 @@ $$
 \end{align*}
 $$
 
-where $Re$ denotes the Reynolds number. In the case of projection methods, difficulties arise in choosing the boundary conditions to be imposed for the Poisson equation which is to be solved at each time step to compute the pressure. An alternative that allows to avoid or reduce some of these problems is the so-called artificial compressibility formulation. In this formulation, the incompressibility constraint is relaxed and a time evolution equation for the pressure is introduced, which is characterized by an artificial sound speed $ c, $ so as to obtain:
+where $Re$ denotes the Reynolds number. In the case of projection methods, difficulties arise in choosing the boundary conditions to be imposed for the Poisson equation which is to be solved at each time step to compute the pressure. An alternative that allows to avoid or reduce some of these problems is the so-called artificial compressibility formulation. In this formulation, the incompressibility constraint is relaxed and a time evolution equation for the pressure is introduced, which is characterized by an artificial sound speed $c$, so as to obtain:
 
 $$
 \begin{align*}
diff --git a/NavierStokes_TRBDF2_DG/navier_stokes_TRBDF2_DG.cc b/NavierStokes_TRBDF2_DG/navier_stokes_TRBDF2_DG.cc
index 434a65e..f47975b 100644
--- a/NavierStokes_TRBDF2_DG/navier_stokes_TRBDF2_DG.cc
+++ b/NavierStokes_TRBDF2_DG/navier_stokes_TRBDF2_DG.cc
@@ -196,6 +196,10 @@ namespace NS_TRBDF2 {
   // the polynomial degree for the velocity, the number of quadrature points for integrals for the pressure step,
   // the number of quadrature points for integrals for the velocity step, the type of vector for storage and the type
   // of floating point data (in general double or float for preconditioners structures if desired).
+  // PM: Number= typename Vec::value_type; ?
+  // PM: you could also remove the template parameters (fe_degree_p, fe_degree_v, n_q_points_1d_p, 
+  //     n_q_points_1d_v); in this case the precompiled versions are used; the penalty should be
+  //     minor; see also step75
   //
   template<int dim, int fe_degree_p, int fe_degree_v, int n_q_points_1d_p, int n_q_points_1d_v, typename Vec, typename Number>
   class NavierStokesProjectionOperator: public MatrixFreeOperators::Base<dim, Vec> {
@@ -391,7 +395,7 @@ namespace NS_TRBDF2 {
   //
   template<int dim, int fe_degree_p, int fe_degree_v, int n_q_points_1d_p, int n_q_points_1d_v, typename Vec, typename Number>
   void NavierStokesProjectionOperator<dim, fe_degree_p, fe_degree_v, n_q_points_1d_p, n_q_points_1d_v, Vec, Number>::
-  set_NS_stage(const unsigned int stage) {
+  set_NS_stage(const unsigned int stage) { // PM: what about an enum?
     AssertIndexRange(stage, 4);
     Assert(stage > 0, ExcInternalError());
 
@@ -705,7 +709,7 @@ namespace NS_TRBDF2 {
         for(unsigned int q = 0; q < phi.n_q_points; ++q) {
           const auto& n_plus                   = phi.get_normal_vector(q);
 
-          const auto& grad_u_old               = phi_old.get_gradient(q);
+          const auto& grad_u_old               = phi_old.get_gradient(q); // PM: replace reference
           const auto& grad_u_int               = phi_int.get_gradient(q);
           const auto& tensor_product_u_n       = outer_product(phi_old.get_value(q), phi_old.get_value(q));
           const auto& tensor_product_u_n_gamma = outer_product(phi_int.get_value(q), phi_int.get_value(q));
@@ -868,6 +872,7 @@ namespace NS_TRBDF2 {
   template<int dim, int fe_degree_p, int fe_degree_v, int n_q_points_1d_p, int n_q_points_1d_v, typename Vec, typename Number>
   void NavierStokesProjectionOperator<dim, fe_degree_p, fe_degree_v, n_q_points_1d_p, n_q_points_1d_v, Vec, Number>::
   vmult_rhs_pressure(Vec& dst, const std::vector<Vec>& src) const {
+    // PM: for(auto & vec : src)
     for(unsigned int d = 0; d < src.size(); ++d)
       src[d].update_ghost_values();
 
@@ -1356,7 +1361,7 @@ namespace NS_TRBDF2 {
                        &NavierStokesProjectionOperator::assemble_face_term_velocity,
                        &NavierStokesProjectionOperator::assemble_boundary_term_velocity,
                        this, dst, src, false,
-                       MatrixFree<dim, Number>::DataAccessOnFaces::unspecified,
+                       MatrixFree<dim, Number>::DataAccessOnFaces::unspecified, // unspecified?
                        MatrixFree<dim, Number>::DataAccessOnFaces::unspecified);
     }
     else if(NS_stage == 2) {
@@ -1940,6 +1945,7 @@ namespace NS_TRBDF2 {
           for(unsigned int j = 0; j < phi.dofs_per_component; ++j)
             phi.submit_dof_value(VectorizedArray<Number>(), j);
           phi.submit_dof_value(make_vectorized_array<Number>(1.0), i);
+          // PM: we have introduced flags in this function, could you use those?
           phi.evaluate(true, true);
 
           for(unsigned int q = 0; q < phi.n_q_points; ++q) {
@@ -1977,6 +1983,7 @@ namespace NS_TRBDF2 {
       this->data->initialize_dof_vector(inverse_diagonal, 0);
       const unsigned int dummy = 0;
 
+      // PM: would you write a function similar to MatrixFreeTools::compute_diagonal() and add it to deal.II?
       this->data->loop(&NavierStokesProjectionOperator::assemble_diagonal_cell_term_velocity,
                        &NavierStokesProjectionOperator::assemble_diagonal_face_term_velocity,
                        &NavierStokesProjectionOperator::assemble_diagonal_boundary_term_velocity,
@@ -2528,12 +2535,13 @@ namespace NS_TRBDF2 {
     /*--- Solve the system ---*/
     SolverControl solver_control(max_its, 1e-12*rhs_u.l2_norm());
     SolverCG<LinearAlgebra::distributed::Vector<double>> cg(solver_control);
-    cg.solve(navier_stokes_matrix, u_tmp, rhs_u, PreconditionIdentity());
+    cg.solve(navier_stokes_matrix, u_tmp, rhs_u, PreconditionIdentity()); // PM: no preconditioner?
   }
 
 
   // The following function is used in determining the maximal velocity
   // in order to compute the Courant number.
+  // PM: why not u_n.linfty_norm()?
   //
   template<int dim>
   double NavierStokesProjection<dim>::get_maximal_velocity() {
@@ -2548,6 +2556,7 @@ namespace NS_TRBDF2 {
   // The following function is used in determining the maximal nodal difference
   // in order to see if we have reched steady-state. We simply use integrate_difference testing
   // u_n - u_n_minus_1 against the zero function.
+  // PM: get maximal difference of what?
   //
   template<int dim>
   double NavierStokesProjection<dim>::get_maximal_difference() {
@@ -2630,6 +2639,7 @@ namespace NS_TRBDF2 {
           velocity and pressure obviously. However, the two dof_handlers are different, so we neede to create an ad-hoc
           iterator for the pressure that we update manually. It is guaranteed that the cells are visited in the same order
           (see the documentation) ---*/
+    // PM: loop over active cells of tria and create DoFCellAccessor on the fly
     auto tmp_cell = dof_handler_pressure.begin_active();
     for(const auto& cell : dof_handler_velocity.active_cell_iterators()) {
       if(cell->is_locally_owned()) {
@@ -2664,8 +2674,8 @@ namespace NS_TRBDF2 {
 
     /*--- At the end, each processor has computed the contribution to the boundary cells it owns and, therefore,
           we need to sum up all the contributions. ---*/
-    double lift = Utilities::MPI::sum(local_lift, MPI_COMM_WORLD);
-    double drag = Utilities::MPI::sum(local_drag, MPI_COMM_WORLD);
+    const double lift = Utilities::MPI::sum(local_lift, MPI_COMM_WORLD);
+    const double drag = Utilities::MPI::sum(local_drag, MPI_COMM_WORLD);
     if(Utilities::MPI::this_mpi_process(MPI_COMM_WORLD) == 0) {
       output_lift << lift << std::endl;
       output_drag << drag << std::endl;
@@ -2696,7 +2706,7 @@ namespace NS_TRBDF2 {
 
     /*--- This is basically the indicator per cell computation (see step-50). Since it is not so complciated
           we implement it through a lambda expression ---*/
-    auto cell_worker = [&](const Iterator&   cell,
+    const auto cell_worker = [&](const Iterator&   cell,
                            ScratchData<dim>& scratch_data,
                            CopyData&         copy_data) {
       FEValues<dim>& fe_values = scratch_data.fe_values; /*--- Here we finally use the 'FEValues' inside ScratchData ---*/
@@ -2718,7 +2728,7 @@ namespace NS_TRBDF2 {
 
     const UpdateFlags cell_flags = update_gradients | update_quadrature_points | update_JxW_values;
 
-    auto copier = [&](const CopyData &copy_data) {
+    const auto copier = [&](const CopyData &copy_data) {
       if(copy_data.cell_index != numbers::invalid_unsigned_int)
         estimated_error_per_cell[copy_data.cell_index] += copy_data.value;
     };
@@ -2794,6 +2804,8 @@ namespace NS_TRBDF2 {
   // Interpolate the locally refined solution to a mesh with maximal resolution
   // and transfer velocity and pressure.
   //
+  // PM: I don't get what this function does.
+  //
   template<int dim>
   void NavierStokesProjection<dim>::interpolate_max_res(const unsigned int level) {
     parallel::distributed::SolutionTransfer<dim, LinearAlgebra::distributed::Vector<double>>
@@ -2847,6 +2859,7 @@ namespace NS_TRBDF2 {
   //
   template<int dim>
   void NavierStokesProjection<dim>::save_max_res() {
+    // PM: use GridTools::coarse_grid()
     parallel::distributed::Triangulation<dim> triangulation_tmp(MPI_COMM_WORLD);
     GridGenerator::plate_with_a_hole(triangulation_tmp, 0.5, 1.0, 1.0, 1.1, 1.0, 19.0, Point<2>(2.0, 2.0), 0, 1, 1.0, 2, true);
     triangulation_tmp.refine_global(triangulation.n_global_levels() - 1);
diff --git a/NavierStokes_TRBDF2_DG/runtime_parameters.h b/NavierStokes_TRBDF2_DG/runtime_parameters.h
index acbe846..e88367c 100644
--- a/NavierStokes_TRBDF2_DG/runtime_parameters.h
+++ b/NavierStokes_TRBDF2_DG/runtime_parameters.h
@@ -58,7 +58,7 @@ namespace RunTimeParameters {
                                 refinement_iterations(0) {
     prm.enter_subsection("Physical data");
     {
-      prm.declare_entry("initial_time",
+      prm.declare_entry("initial_time", // PM: rather use add_parameter()
                         "0.0",
                         Patterns::Double(0.0),
                         " The initial time of the simulation. ");
```

Personally, I would not use `set_NS_stage()`+jump tables but rather create separate operators; but I guess this is personal taste.

One question: according to your paper, you are doing DG+AMR+MF+MG? Is that working for you? As far as I remember, this is not working only if you switch to a partly matrix-based implementation at the edges (https://github.com/dealii/dealii/blob/990806d4655955a1eae35274f8111dedcbbab034/include/deal.II/multigrid/multigrid.templates.h#L138-L144).

**Comment by peterrum** [comment]
I have fixed some warnings.

**Comment by peterrum** [comment]
@GiuseppeOrlando878776 The code is online: https://www.dealii.org/developer/doxygen/deal.II/code_gallery_NavierStokes_TRBDF2_DG.html. Could you check why some formulas are not displayed correctly. THanks!

**Comment by GiuseppeOrlando878776** [comment]
Thanks a lot. I'm sorry for the delay in the answer, but I was quite busy in a conference from which I just came back (and I'm going to join another one tomorrow). I will try to check as soon as possible which are the problems for the visualization in order to fix them as well as to try some of the proper "coding design" suggestions I received. I take this opportunity to answer some of the main questions:

1. In the "projection" of the pressure gradient into the velocity space, I solved the system without preconditioned both because I noticed from some attempts that the non-preconditioned version was in some cases faster and because to avoid another 'else' condition in the compute_diagonal (even though very similar to the other ones)
2. I used "MatrixFree<dim, Number>::DataAccessOnFaces::unspecified" because in the debug mode, I got some errors when specifying different flags. For sure, it is a problem related to the fact I was not able to use properly them, so I decided to switch to the more "conservative" which works for sure.
3. I have no problems in writing a function similar to MatrixFreeTools::compute_diagonal(); I will first try it into my code version, then is it necessary to do something in order to be ready to be in case added in deal.II?
4. I was not aware about the potential issue DG+MG+MF; however in my numerical experiments I did not notice any particular issue and we also tried to make some quantitative analysis to verify the effectiveness of AMR. For instance in the article, the velocity field of the adaptive version is compared to the one with a uniform resolution (this is what the 'interpolate_max_res()' routine does, namely it interpolates the variables computed with the adaptive grid to a uniform grid with a resolution equal to the maximal one of the adaptive mesh) and, basically, no difference occurs. This approach has been tested also in other applications without significant issues: in this preprint (https://arxiv.org/pdf/2111.13167.pdf), which presents an extension of this code to the compressible Navier-Stokes, a quantitative comparison especially in Section 7.4 is present, and it has also been used for the 2D cases of this other work (https://arxiv.org/pdf/2204.08693.pdf).

Best

**Comment by GiuseppeOrlando878776** [comment]
Good morning, I have corrected the mathematical formulas in the "README.md" file and I have also done small modifications trying some of the suggestions received to improve the code (use of EvaluationFlags, a small modification of template parameters...). Do you want me to open a new pull-request to include these changes? 
Moreover, I created a new branch (https://github.com/GiuseppeOrlando878776/code-gallery/tree/ComputeDiagonal_NS_TRBDF2_DG/NavierStokes_TRBDF2_DG) where I tested a 'compute_diagonal' function with a syntax closer to the routing already present in deal.ii; I do not know if it can be useful (I have still to test it in depth, but it seems to work).

Best

**Pull request merged**
